language: go
sudo: false
go:
  - 1.5
  - tip

env:
  - GOARCH=amd64

script:
  - go version
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go test -v -covermode=count -coverprofile=coverage.out github.com/wookay/gocat

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 3Qxq8BSNJVqxHp73o69y0Tn7gtnjVQJWB

notifications:
  email: false
