language: go
go:
  - 1.5.1
sudo: required
dist: trusty
env:
  - GIMME_OS=linux GIMME_ARCH=amd64

install:
  - go version
  - go get -d -v ./...

script:
  - GIMME_GO_VERSION=1.5 gimme --list
  - go build -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go get github.com/boltdb/bolt
  - go get github.com/nlopes/slack
  - go test -v -covermode=count -coverprofile=coverage.out github.com/wookay/gocat

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 3Qxq8BSNJVqxHp73o69y0Tn7gtnjVQJWB

notifications:
  email: false
